"""
backend/routers/export_jira.py — Export test cases to Jira Cloud / Server
"""
import base64
import json
import requests
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional
from backend.db import get_conn

router = APIRouter()


class JiraConfig(BaseModel):
    jira_url: str
    email: str
    api_token: str
    project_key: str
    issue_type: str = "Task"


class JiraExportRequest(JiraConfig):
    user_story: str
    tc_list: list
    label: Optional[str] = ""


class JiraHistoryRequest(JiraConfig):
    run_id: str


def _auth_headers(email: str, token: str) -> dict:
    creds = base64.b64encode(f"{email}:{token}".encode()).decode()
    return {
        "Authorization": f"Basic {creds}",
        "Content-Type":  "application/json",
        "Accept":        "application/json",
    }


def _adf_paragraph(text: str) -> dict:
    return {
        "type": "paragraph",
        "content": [{"type": "text", "text": str(text)[:2000]}],
    }


def _adf_heading(text: str, level: int = 3) -> dict:
    return {
        "type": "heading",
        "attrs": {"level": level},
        "content": [{"type": "text", "text": text}],
    }


def _build_description(tc: dict, user_story: str) -> dict:
    steps    = str(tc.get("Test Steps")    or tc.get("test_steps")    or tc.get("Steps")    or "—")
    expected = str(tc.get("Expected Result") or tc.get("expected_result") or "—")
    category = str(tc.get("Category")     or tc.get("category")     or "")
    risk     = str(tc.get("Risk Level")   or tc.get("risk_level")   or tc.get("Risk")     or "")
    priority = str(tc.get("Priority")     or tc.get("priority")     or "Medium")
    return {
        "version": 1,
        "type": "doc",
        "content": [
            _adf_heading("User Story Context", 3),
            _adf_paragraph(user_story[:600]),
            _adf_heading("Test Details", 3),
            _adf_paragraph(f"Category: {category}  |  Priority: {priority}  |  Risk Level: {risk}"),
            _adf_heading("Test Steps", 3),
            _adf_paragraph(steps),
            _adf_heading("Expected Result", 3),
            _adf_paragraph(expected),
            {
                "type": "paragraph",
                "content": [{
                    "type": "text",
                    "text": "Generated by QA Ninjas — Agentic AI Test Suite Generator",
                    "marks": [{"type": "em"}],
                }],
            },
        ],
    }


PRIORITY_MAP = {
    "critical": "Highest",
    "high":     "High",
    "medium":   "Medium",
    "low":      "Low",
}


def _fetch_run(run_id: str) -> dict:
    with get_conn() as conn:
        row = conn.execute("SELECT * FROM runs WHERE id=?", (run_id,)).fetchone()
    if not row:
        raise HTTPException(status_code=404, detail="Run not found")
    data = dict(row)
    for key in ("tc_list", "report_data", "review_data"):
        try:
            data[key] = json.loads(data[key] or "null") or ([] if key == "tc_list" else {})
        except Exception:
            data[key] = [] if key == "tc_list" else {}
    if "label" not in data or data["label"] is None:
        data["label"] = ""
    return data


@router.post("/api/export/jira/test")
def test_jira_connection(req: JiraConfig):
    base = req.jira_url.rstrip("/")
    headers = _auth_headers(req.email, req.api_token)
    try:
        r = requests.get(f"{base}/rest/api/3/myself", headers=headers, timeout=10)
        if r.status_code != 200:
            return {"success": False,
                    "error": f"Auth failed ({r.status_code}). Check URL, email and API token."}
        user = r.json()
        pr = requests.get(f"{base}/rest/api/3/project/search?maxResults=20",
                          headers=headers, timeout=10)
        projects = [p["key"] for p in pr.json().get("values", [])] if pr.ok else []
        return {
            "success":      True,
            "display_name": user.get("displayName", ""),
            "email":        user.get("emailAddress", ""),
            "projects":     projects,
        }
    except Exception as e:
        return {"success": False, "error": str(e)}


def _do_jira_export(req: JiraExportRequest) -> dict:
    base    = req.jira_url.rstrip("/")
    headers = _auth_headers(req.email, req.api_token)
    run_label = (req.label or "QA-Ninjas").replace(" ", "_")[:50]

    check = requests.get(f"{base}/rest/api/3/myself", headers=headers, timeout=10)
    if check.status_code != 200:
        return {
            "success": False,
            "error":   f"Authentication failed ({check.status_code}). "
                       "Verify your Jira URL, email, and API token.",
        }

    created, failed = [], []

    for tc in req.tc_list:
        test_key = str(tc.get("Test Key") or tc.get("test_key") or "")
        summary  = str(tc.get("Summary")  or tc.get("summary")  or "Test Case")
        priority_raw = str(tc.get("Priority") or tc.get("priority") or "Medium")
        jira_priority = PRIORITY_MAP.get(priority_raw.lower(), "Medium")

        payload = {
            "fields": {
                "project":     {"key": req.project_key},
                "summary":     f"[{test_key}] {summary}" if test_key else summary,
                "description": _build_description(tc, req.user_story),
                "issuetype":   {"name": req.issue_type},
                "priority":    {"name": jira_priority},
                "labels":      [run_label, "QA-Ninjas", "automated-qa"],
            }
        }

        try:
            resp = requests.post(
                f"{base}/rest/api/3/issue",
                headers=headers, json=payload, timeout=20,
            )
            if resp.status_code in (200, 201):
                key = resp.json().get("key", "")
                created.append({
                    "key":     key,
                    "url":     f"{base}/browse/{key}",
                    "summary": summary,
                })
            else:
                failed.append({"summary": summary, "error": resp.text[:300]})
        except Exception as e:
            failed.append({"summary": summary, "error": str(e)})

    return {
        "success":     True,
        "created":     len(created),
        "failed":      len(failed),
        "issues":      created,
        "errors":      failed,
        "project_url": f"{base}/projects/{req.project_key}",
    }


@router.post("/api/export/jira")
def export_to_jira(req: JiraExportRequest):
    return _do_jira_export(req)


@router.post("/api/export/jira/history")
def export_history_to_jira(req: JiraHistoryRequest):
    data = _fetch_run(req.run_id)
    payload = JiraExportRequest(
        jira_url=req.jira_url,
        email=req.email,
        api_token=req.api_token,
        project_key=req.project_key,
        issue_type=req.issue_type,
        user_story=data.get("user_story", ""),
        tc_list=data.get("tc_list", []),
        label=data.get("label", "") or data.get("preview", "")[:40],
    )
    return _do_jira_export(payload)
